FlightsManager/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FlightsManager.Controllers
{
    /// <summary>
    /// The controller for all employees.
    /// </summary>
    public class EmployeeController : Controller
    {
        /// <summary>
        /// The Index method for the controller.
        /// </summary>
        /// <returns>A view of Index.</returns>
        [Authorize(Roles ="Employee, Admin")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

FlightsManager/Controllers/FlightController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FlightsManager.Data;
using FlightsManager.Models.Base;
using FlightsManager.Models.Flight;
using FlightsManager.Models.Reservation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FlightsManager.Controllers
{
    /// <summary>
    /// The controller for all flights.
    /// </summary>
    [Authorize(Roles = "Employee, Admin")]
    public class FlightController : Controller
    {
        private readonly ApplicationDbContext db;
        private const int PageSize = 10;

        /// <summary>
        /// The default constructor of the controller.
        /// </summary>
        /// <remarks>
        /// When initiated, the controller connects to the database.
        /// </remarks>
        public FlightController()
        {
            this.db = new ApplicationDbContext();
        }

        /// <summary>
        /// The Index method.
        /// </summary>
        /// <param name="model">The Index view.</param>
        /// <returns>A view of all flights.</returns>
        public async Task<IActionResult> Index(FlightIndexVM model)
        {
            model.Pager ??= new PagerVM();
            model.Pager.CurrentPage = model.Pager.CurrentPage <= 0 ? 1 : model.Pager.CurrentPage;

            List<FlightVM> items = await db.Flight
                .Skip((model.Pager.CurrentPage - 1) * PageSize)
                .Take(PageSize)
                .Select(f => new FlightVM()
                {
                    AirplaneID = f.AirplaneID,
                    DestinationFrom = f.DestinationFrom,
                    DestinationTo = f.DestinationTo,
                    TakesOff = f.TakesOff,
                    ContiniusFlight = f.Landing.Subtract(f.TakesOff),
                    AirplaneType = f.AirplaneType,
                    PilotName = f.PilotName,
                    Capacity = f.Capacity,
                    BusinessClassCapacity = f.BusinessClassCapacity,
                    Reservations = null
                }).ToListAsync();

            model.Items = items;
            model.Pager.PagesCount = (int)Math.Ceiling(await db.Flight.CountAsync() / (double)PageSize);

            return View(model);
        }

        /// <summary>
        /// Method that returns a view where a flight can be created.
        /// </summary>
        /// <returns>The said view.</returns>
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            FlightCreateVM model = new FlightCreateVM();

            return View(model);
        }

        /// <summary>
        /// Method through which a flight is created.
        /// </summary>
        /// <param name="model">The view where the info is stored.</param>
        /// <returns>If the info is valid, the method redirects to Index. If not, it returns to the same view.</returns>
        [HttpPost]
        public async Task<IActionResult> Create(FlightCreateVM model)
        {
            Guid id = Guid.NewGuid();

            if (ModelState.IsValid)
            {
                Flight flight = new Flight
                {
                    AirplaneID = id.ToString(),
                    DestinationFrom = model.DestinationFrom,
                    DestinationTo = model.DestinationTo,
                    TakesOff = model.TakesOff,
                    Landing = model.Landing,
                    AirplaneType = model.AirplaneType,
                    PilotName = model.PilotName,
                    Capacity = model.Capacity,
                    BusinessClassCapacity = model.BusinessClassCapacity,
                    Reservations = null
                };

                db.Add<Flight>(flight);
                await db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        /// <summary>
        /// Method that returns the view where a flight can be edited through.
        /// </summary>
        /// <param name="id">The ID of the requested flight.</param>
        /// <returns>If successful, the method returns the view. If the id is not correct or if the flight is not found - a NotFound result.</returns>
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Edit(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Flight model = await db.Flight.FindAsync(id);

            if (model == null)
            {
                return NotFound();
            }

            FlightEditVM flight = new FlightEditVM
            {
                AirplaneID = model.AirplaneID,
                DestinationFrom = model.DestinationFrom,
                DestinationTo = model.DestinationTo,
                TakesOff = model.TakesOff,
                Landing = model.Landing,
                AirplaneType = model.AirplaneType,
                PilotName = model.PilotName,
                Capacity = model.Capacity,
                BusinessClassCapacity = model.BusinessClassCapacity,
                Reservations = model.Reservations
            };

            return View(flight);
        }

        /// <summary>
        /// Method that edits a flight.
        /// </summary>
        /// <param name="model">The view containing the new info.</param>
        /// <returns>If successful, the method redirects back to Index. If the info isn't valid, it returns back the view. If the flight is not found - a NotFound result.</returns>
        [HttpPost]
        public async Task<IActionResult> Edit(FlightEditVM model)
        {
            int minOrdinaryTickets = 0;
            int minBusinessTickets = 0;

            List<Reservation> reservations = db.Reservation
                .Where(r => r.FlightID == model.AirplaneID)
                .ToList();
            List<ApplicationUser> passangers = new List<ApplicationUser>();

            foreach (var reservation in reservations)
            {
                List<ApplicationUser> passangersLoop = db.ApplicationUser.Where(p => p.ReservationID == reservation.ID).ToList();
                foreach (var passanger in passangersLoop)
                {
                    passangers.Add(passanger);
                    if (passanger.TicketType == "Ordinary")
                    {
                        minOrdinaryTickets++;
                    }
                    else
                    {
                        minBusinessTickets++;
                    }
                }
            }

            if (minBusinessTickets > model.BusinessClassCapacity || minOrdinaryTickets > model.Capacity)
            {
                model.IsFirstTime = false;
                model.Message = $"You have {minOrdinaryTickets} reserved ordinary tickets and {minBusinessTickets} reserved business tickets. Please do not edit ordinary and business tickets less than that!";

                return View(model);
            }
            else
            {
                if (ModelState.IsValid)
                {
                    Flight flight = await db.Flight.FindAsync(model.AirplaneID);

                    flight.AirplaneID = flight.AirplaneID;
                    flight.DestinationFrom = model.DestinationFrom;
                    flight.DestinationTo = model.DestinationTo;
                    flight.TakesOff = model.TakesOff;
                    flight.Landing = model.Landing;
                    flight.AirplaneType = model.AirplaneType;
                    flight.PilotName = model.PilotName;
                    flight.Capacity = model.Capacity;
                    flight.BusinessClassCapacity = model.BusinessClassCapacity;
                    flight.Reservations = model.Reservations;

                    try
                    {
                        db.Update(flight);
                        reservations.ForEach(r => db.Add(r));
                        passangers.ForEach(p => db.Add(p));
                        await db.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        bool isExist = db.Flight.Any(f => f.AirplaneID == flight.AirplaneID);

                        if (!isExist)
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }

                    return RedirectToAction(nameof(Index));
                }
            }
            return View();
        }

        /// <summary>
        /// Method that returns a view of all the flight's reservations.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>The said view.</returns>
        public IActionResult Detail(string? id)
        {
            List<Reservation> reservations = db.Reservation
                .Where(r => r.FlightID == id)
                .ToList();

            List<ReservationDetailVM> list = new List<ReservationDetailVM>();

            for (int i = 0; i < reservations.Count; i++)
            {
                ReservationDetailVM reservationDetail = new ReservationDetailVM()
                {
                    Items = db.ApplicationUser
                        .Where(p => p.ReservationID == reservations[i].ID)
                        .Select(p => new ReservationVM()
                        {
                            FirstName = p.FirstName,
                            MiddleName = p.MiddleName,
                            LastName = p.LastName,
                            Email = p.Email,
                            Nationality = p.Nationality,
                            PIN = p.UserPIN,
                            TelephoneNumber = p.PhoneNumber,

FlightsManager/Controllers/RoleController.cs
using FlightsManager.Data;
using FlightsManager.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FlightsManager.Controllers
{
    /// <summary>
    /// The controller for all the user roles.
    /// </summary>
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private RoleManager<IdentityRole> _roleManager;
        private ApplicationDbContext _dbContext;


        /// <summary>
        /// The constructor for the controller.
        /// </summary>
        /// <param name="roleManager">Provides the APIs for managing the roles.</param>
        /// <param name="dbContext">The database context.</param>
        public RoleController(RoleManager<IdentityRole> roleManager, ApplicationDbContext dbContext)
        {
            this._roleManager = roleManager;
            this._dbContext = dbContext;
        }

        /// <summary>
        /// Method that returns the view where a role can be created.
        /// </summary>
        /// <returns>The said view.</returns>
        public IActionResult Create()
        {
            return View(new IdentityRole());
        }

        /// <summary>
        /// Method that creates a role.
        /// </summary>
        /// <param name="role">The view containing the new role.</param>
        /// <returns>Redirects to Index.</returns>
        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            await _roleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// The method for Index.
        /// </summary>
        /// <returns>A view containing all the roles.</returns>
        public async Task<IActionResult> Index()
        {
            List<IdentityRole> roles = await _roleManager.Roles.ToListAsync();
            var userRoles = new List<UserRolesViewModel>();

            foreach (var role in roles)
            {
                var allRoles = new UserRolesViewModel
                {
                    RoleId = role.Id, RoleName = role.Name
                };
                userRoles.Add(allRoles);
            }
            return View(userRoles);
        }

        /// <summary>
        /// Method that returns a view through which the name of a role can be edited.
        /// </summary>
        /// <param name="id">ID of the requested role.</param>
        /// <returns>If the role is found, the method returns a view of the role. If not - a NotFound result.</returns>
        [HttpGet]
        public async Task<IActionResult> EditRoleName(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return NotFound();
            }


            var userRoles = new UserRolesViewModel
            {
                RoleId = role.Id,
                RoleName = role.Name
            };

            return View(userRoles);
        }

        /// <summary>
        /// Method that edits a role's name.
        /// </summary>
        /// <param name="rolesViewModel">The view containing the new role name.</param>
        /// <returns>If successful, the method redirects back to Index. If not, it returns back the view. If the role is not found - a NotFound result.</returns>
        [HttpPost]
        public async Task<IActionResult> EditRoleName(UserRolesViewModel rolesViewModel)
        {
            var role = await _roleManager.FindByIdAsync(rolesViewModel.RoleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {rolesViewModel.RoleId} cannot be found";
                return NotFound();
            }
            else
            {
                role.Id = rolesViewModel.RoleId;
                role.Name = rolesViewModel.RoleName;
             
                var result = await _roleManager.UpdateAsync(role);
                _dbContext.SaveChanges();

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View(rolesViewModel);
            }
        }

        /// <summary>
        /// Method that deletes a role.
        /// </summary>
        /// <param name="id">The ID of the requested role.</param>
        /// <returns>If the role is deleted, the method redirects to Index. If not, it again redirects to Index. If the role is not found, the method returns a NotFound result.</returns>
            public async Task<IActionResult> Delete(string id)

            {
                IdentityRole role = await _roleManager.FindByIdAsync(id);

                if (role != null)
                {
                    IdentityResult result = await _roleManager.DeleteAsync(role);
                    await _dbContext.SaveChangesAsync();

                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return NotFound();
                    }

                }
                else
                {
                    ModelState.AddModelError("", "Role not found");
                }
                return View("Index");
            }
        }
    }

FlightsManager/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - Admin</title>
    <link href="~/admin-theme/dist/css/styles.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4-4.1.1/dt-1.10.24/b-1.7.0/date-1.0.3/fc-3.3.2/fh-3.1.8/r-2.2.7/sc-2.0.3/sb-1.0.1/sp-1.2.2/sl-1.3.3/datatables.min.css" />
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark" style="background: rgb(12,26,63); background: linear-gradient(102deg, rgba(12,26,63,1) 0%, rgba(11,97,130,1) 100%);">
        <a class="navbar-brand" asp-controller="Admin" asp-action="Index">Admin Dashboard</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <form class="dropdown-item" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                        <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                    </form>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion" style="background: rgb(12,26,63); background: linear-gradient(102deg, rgba(12,26,63,1) 0%, rgba(11,97,130,1) 100%);">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Admin</div>
                        <a class="nav-link" asp-controller="Admin" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <div class="sb-sidenav-menu-heading">Pages</div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#userDropdown" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Users
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="userDropdown" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <ul>
                                    <li class="nav-item">
                                        <a class="nav-link text-light font-weight-light" asp-area="" asp-controller="Admin" asp-action="Create">Create new user</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-light font-weight-light" asp-area="" asp-controller="Admin" asp-action="UserList">Edit users</a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#roles" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Roles
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="roles" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <ul>
                                    <li class="nav-item">
                                        <a class="nav-link text-light font-weight-light" asp-area="" asp-controller="Role" asp-action="Create">Create new user role</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-light font-weight-light" asp-area="" asp-controller="Role" asp-action="Index">Edit roles</a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#reservations" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Reservations
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="reservations" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <ul>
                                    <!--
                                        <li class="nav-item">
                                        <a class="nav-link text-light font-weight-light" asp-area="" asp-controller="Reservation" asp-action="PassangerCount">Create reservation</a>
                                    </li>

                                    -->
                                    <li class="nav-item">
                                        <a class="nav-link text-light font-weight-light" asp-area="" asp-controller="Reservation" asp-action="Index">All reservations</a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#flights" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Flights
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="flights" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <ul>
                                    <li class="nav-item">
                                        <a class="nav-link text-light font-weight-light" asp-area="" asp-controller="Flight" asp-action="Create">Create flight</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-light font-weight-light" asp-area="" asp-controller="Flight" asp-action="Index">All flights</a>
                                    </li>
                                </ul>
                            </nav>
                        </div>

                    </div>

                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                @RenderSection("Scripts", required: false)
                @RenderBody()
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Flights Manager 2021</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>

    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="/admin-theme/dist/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="/assets/demo/chart-area-demo.js"></script>
    <script src="/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="/assets/demo/datatables-demo.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4-4.1.1/dt-1.10.24/b-1.7.0/date-1.0.3/fc-3.3.2/fh-3.1.8/r-2.2.7/sc-2.0.3/sb-1.0.1/sp-1.2.2/sl-1.3.3/datatables.min.js"></script>
    <script src="/js/site.js" asp-append-version="true"></script>

</body>
</html>